spring:
  application:
    name: authentication-service
  data:
    mongodb:
      username: ${MONGODB_USER_NAME:test}
      password: ${MONGODB_PASSWORD:test}
      database: ${MONGODB_DATABASE:test}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}
      host: ${MONGODB_HOSTNAME:localhost}
      port: ${MONGODB_PORT:27017}
      auto-index-creation: true

eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    #ip-address: ${AUTHENTICATION_SERVICE_IP:192.168.1.1} #强制指定IP地址，默认会获取本机的IP地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

